import java.util.Properties

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.kotlin.multiplatform.library) apply false
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.compose.multiplatform) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.ksp) apply false
}

/**
 * Writes `version.properties` into the xcconfig the Xcode project reads.
 *
 * The Android build reads `version.properties` directly, so it can never drift.
 * Xcode cannot read a `.properties` file, so this generates the one file it
 * can. It runs as part of `:androidApp:assemble*` and can be invoked on its own
 * with `./gradlew syncIosVersion`.
 */
val syncIosVersion by tasks.registering {
    val source = layout.projectDirectory.file("version.properties")
    val target = layout.projectDirectory.file("iosApp/Version.xcconfig")
    inputs.file(source)
    outputs.file(target)
    doLast {
        val version = Properties().apply {
            source.asFile.inputStream().use { load(it) }
        }
        target.asFile.writeText(
            """
            // Generated by `./gradlew syncIosVersion` from ../version.properties.
            // Do not edit: change version.properties and re-run the task.
            MARKETING_VERSION = ${version.getProperty("versionName")}
            CURRENT_PROJECT_VERSION = ${version.getProperty("versionCode")}
            """.trimIndent() + "\n"
        )
    }
}
